### ISSUE TITLE
OpenWeatherMap API

### ISSUE THREAD

**Issue by sbuljat** [nikolaknezevic120/pzw2#2]
Obzirom da često pozivate OWM API iz različitih kontrolerskih akcija, poželjno bi bilo da taj dio programskog koda izdvojite u zasebnu metodu koju ćete pozivati s različitih mjesta. Zašto? Zbog [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself) principa.

**Comment by sbuljat** [comment]
@nikolaknezevic120 Jeste pogledali ovo?

**Comment by nikolaknezevic120** [comment]
Pozdrav, procitao sam mail ali nisam stigao popraviti ni raditi na zavrsnom
projektu. Nadam se kroz ovaj tjedan zavrsit sve.

ned, 7. velj 2021. 22:21 Stjepan Buljat <notifications@github.com> je
napisao:
